/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AlignmentCandidate {
  applied: Generated<boolean>;
  applied_on: string | null;
  candidate_id: string;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision: Generated<string>;
  id: ColumnType<string, never, never>;
  legacy_grist_id: number | null;
  note: string | null;
  payload: Generated<Json>;
  person_id: string;
  pushed_on: string | null;
  score: Numeric | null;
  source: string;
  updated_at: Generated<Timestamp>;
}

export interface AuditLog {
  action: string;
  actor: string | null;
  after: Json | null;
  at: Generated<Timestamp>;
  before: Json | null;
  id: ColumnType<string, never, never>;
  row_id: string | null;
  table_name: string;
}

export interface BenchmarkPeerGroup {
  id: ColumnType<string, never, never>;
  name: string;
  owner: string;
  rors: Generated<string[]>;
  updated_at: Generated<Timestamp>;
}

export interface Establishment {
  created_at: Generated<Timestamp>;
  extra: Generated<Json>;
  id: ColumnType<string, never, never>;
  idref: string | null;
  label: string | null;
  legacy_grist_id: number | null;
  name: string;
  ror: string | null;
  uai: string | null;
  updated_at: Generated<Timestamp>;
}

export interface IdentifierConflict {
  people: Int8 | null;
  person_ids: string[] | null;
  scheme: string | null;
  value: string | null;
}

export interface ImportBatch {
  created_at: Generated<Timestamp>;
  id: ColumnType<string, never, never>;
  label: string | null;
  legacy_table: string | null;
  source: string;
}

export interface ImportRow {
  batch_id: Int8;
  choice: string | null;
  current_value: string | null;
  family: string | null;
  field: string;
  id: ColumnType<string, never, never>;
  imported_json: Json | null;
  imported_value: string | null;
  lab: string | null;
  legacy_grist_id: number | null;
  other_value: string | null;
  person_id: string | null;
  person_label: string | null;
  remark: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
}

export interface Membership {
  created_at: Generated<Timestamp>;
  end_date: string | null;
  end_upper: ColumnType<string | null, never, never>;
  id: ColumnType<string, never, never>;
  lab_label: string | null;
  legacy_grist_id: number | null;
  person_id: string;
  role: string | null;
  source: string | null;
  start_date: string | null;
  start_lower: ColumnType<string | null, never, never>;
  structure_id: Int8 | null;
  team_labels: Generated<string[]>;
  type: string | null;
  updated_at: Generated<Timestamp>;
}

export interface MembershipTeam {
  membership_id: Int8;
  team_structure_id: Int8;
}

export interface MergeLog {
  author: string | null;
  dropped_snapshot: Json;
  id: ColumnType<string, never, never>;
  kept_before: Generated<Json>;
  kept_patch: Generated<Json>;
  kept_person_id: string | null;
  legacy_dropped_rowid: number | null;
  legacy_grist_id: number | null;
  legacy_kept_rowid: number | null;
  legacy_restored_rowid: number | null;
  merged_at: Generated<Timestamp>;
  note: string | null;
  restored: Generated<boolean>;
  restored_person_id: string | null;
  uid: string | null;
}

export interface Person {
  birth_date: string | null;
  civility: string | null;
  corps_grade: string | null;
  created_at: Generated<Timestamp>;
  directory_url: string | null;
  doctoral_school: string | null;
  email: string | null;
  employer_id: Int8 | null;
  employment_end: string | null;
  employment_end_upper: ColumnType<string | null, never, never>;
  employment_start: string | null;
  employment_start_lower: ColumnType<string | null, never, never>;
  employment_type: string | null;
  employment_type_label: string | null;
  extra: Generated<Json>;
  first_name: string | null;
  fte_ratio: Numeric | null;
  fte_research: Numeric | null;
  hdr: string | null;
  hdr_year: number | null;
  hr_id: string | null;
  id: Generated<string>;
  last_name: string;
  ldap_state: string | null;
  legacy_grist_id: number | null;
  nationality: string | null;
  note: string | null;
  photo_url: string | null;
  presence_status: string | null;
  presence_validated: Generated<boolean>;
  presence_validated_by: string | null;
  presence_validated_on: string | null;
  presence_validation_scope: Generated<string[]>;
  presence_validation_source: string | null;
  sources: Generated<string[]>;
  uid: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PersonIdentifier {
  checked_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: ColumnType<string, never, never>;
  is_primary: Generated<boolean>;
  person_id: string;
  scheme: string;
  source: string | null;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface PersonIdentifierCheck {
  checked_at: Generated<Timestamp>;
  person_id: string;
  result: string;
  scheme: string;
}

export interface PersonLink {
  created_at: Generated<Timestamp>;
  id: ColumnType<string, never, never>;
  kind: string;
  person_id: string;
  url: string;
}

export interface RefCorpsGrade {
  category: string | null;
  code: string;
  extra: Generated<Json>;
  label: string | null;
}

export interface Report {
  created_at: Generated<Timestamp>;
  definition: Json;
  deleted_at: Timestamp | null;
  description: string | null;
  id: ColumnType<string, never, never>;
  legacy_grist_id: number | null;
  name: string;
  owner: string;
  published_template: Generated<boolean>;
  template_id: string | null;
  updated_at: Generated<Timestamp>;
  visibility: Generated<string>;
}

export interface ReportGeneration {
  ai_texts: Json | null;
  data_date: string | null;
  definition_snapshot: Json | null;
  generated_at: Generated<Timestamp>;
  generated_by: string | null;
  id: ColumnType<string, never, never>;
  pdf_ref: string | null;
  publication_count: number | null;
  report_id: Int8;
  shared_frozen: Generated<boolean>;
}

export interface ReportShare {
  granted_at: Generated<Timestamp>;
  granted_by: string | null;
  grantee: string;
  id: ColumnType<string, never, never>;
  report_id: Int8;
  role: string;
}

export interface Structure {
  acronym: string | null;
  created_at: Generated<Timestamp>;
  establishment_id: Int8 | null;
  extra: Generated<Json>;
  id: ColumnType<string, never, never>;
  idref: string | null;
  legacy_grist_id: number | null;
  level: string | null;
  local_id: string;
  name: string | null;
  nature: string | null;
  parent_id: Int8 | null;
  rnsr: string | null;
  ror: string | null;
  type: string | null;
  updated_at: Generated<Timestamp>;
  url: string | null;
}

export interface SyncState {
  changed_fields: Generated<string[]>;
  last_run: string | null;
  person_id: string;
  source: string;
}

export interface Task {
  assignee: string | null;
  base: string | null;
  channel: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  done_at: Timestamp | null;
  done_by: string | null;
  id: ColumnType<string, never, never>;
  key: string | null;
  lab: string | null;
  legacy_grist_id: number | null;
  link: string | null;
  origin: string | null;
  person_id: string | null;
  person_name: string | null;
  priority: Generated<string>;
  resolution: string | null;
  status: Generated<string>;
  taken_at: Timestamp | null;
  taken_by: string | null;
  title: string;
  type: string;
  uid: string | null;
  updated_at: Generated<Timestamp>;
  verified_at: Timestamp | null;
  waiting_reason: string | null;
}

export interface TaskEvent {
  action: string;
  at: Generated<Timestamp>;
  author: string | null;
  detail: string | null;
  id: ColumnType<string, never, never>;
  task_id: Int8;
}

export interface DB {
  alignment_candidate: AlignmentCandidate;
  audit_log: AuditLog;
  benchmark_peer_group: BenchmarkPeerGroup;
  establishment: Establishment;
  identifier_conflict: IdentifierConflict;
  import_batch: ImportBatch;
  import_row: ImportRow;
  membership: Membership;
  membership_team: MembershipTeam;
  merge_log: MergeLog;
  person: Person;
  person_identifier: PersonIdentifier;
  person_identifier_check: PersonIdentifierCheck;
  person_link: PersonLink;
  ref_corps_grade: RefCorpsGrade;
  report: Report;
  report_generation: ReportGeneration;
  report_share: ReportShare;
  structure: Structure;
  sync_state: SyncState;
  task: Task;
  task_event: TaskEvent;
}
