-- migrate:up
-- Stable ids (lot 6 of druid-internal docs/plan-migration-postgresql.md): the import gives each row of a table that
-- comes from ONE Grist table its Grist row id, so that every id the application already exposes keeps its value —
-- record ids (gristRowId of the memberships), structures `S-<id>`, tasks, reports, merge log entries — and with them
-- the URLs, saved reports and exports that hold them. New rows take the next values of the sequences (the import
-- moves them past the imported ids). Identity columns become GENERATED BY DEFAULT to accept those ids.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['establishment', 'structure', 'membership', 'merge_log', 'task', 'task_event', 'report',
                           'report_share', 'report_generation', 'benchmark_peer_group'] LOOP
    EXECUTE format('ALTER TABLE %I ALTER COLUMN id SET GENERATED BY DEFAULT', t);
  END LOOP;
END $$;

-- The uid keeps its case: about 800 LDAP uids are upper-case (E12A345B), and the application uses them as they are
-- (public ids, URLs, LDAP cache keys). Unique regardless of case, as before.
ALTER TABLE person DROP CONSTRAINT person_uid_check;
ALTER TABLE person DROP CONSTRAINT person_uid_key;
CREATE UNIQUE INDEX person_uid_ci ON person (lower(uid));

-- migrate:down
DROP INDEX person_uid_ci;
UPDATE person SET uid = lower(uid);
ALTER TABLE person ADD CONSTRAINT person_uid_key UNIQUE (uid);
ALTER TABLE person ADD CONSTRAINT person_uid_check CHECK (uid = lower(uid));
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['establishment', 'structure', 'membership', 'merge_log', 'task', 'task_event', 'report',
                           'report_share', 'report_generation', 'benchmark_peer_group'] LOOP
    EXECUTE format('ALTER TABLE %I ALTER COLUMN id SET GENERATED ALWAYS', t);
  END LOOP;
END $$;
