import React, { useEffect, useMemo, useState } from 'react';
import { ScanSearch, RefreshCw, UserCheck, CheckSquare, Square, Copy, GitMerge } from 'lucide-react';
import type { LdapCandidatesDiff, LdapResolved } from '../../lib/gristService';
import { getGradeFromNcorps } from '../../lib/gradeTypology';
import { Trans, Plural, useLingui } from '@lingui/react/macro';
import { i18n } from '@lingui/core';
import { msg } from '@lingui/core/macro';
import { translateApiError } from '../../lib/apiErrors';

/** Progress tracking of the LDAP search (/api/sync-ldap-candidates-progress endpoint). */
export interface LdapCandProgress {
  running: boolean;
  total?: number;
  done?: number;
  matched?: number;
  ambiguous?: number;
  error?: string;
}

interface Props {
  diff: LdapCandidatesDiff | null;
  progress: LdapCandProgress | null;
  applying: boolean;
  /** Relaunches the LDAP search server-side then recomputes the diff. */
  onRerun: () => void;
  /** Applies the attachment of the resolved entries (checked proposals + arbitrated homonyms). */
  onApply: (entries: LdapResolved[]) => void;
  /** Opens the merge assistant (record without uid + row already carrying the uid in the same lab). */
  onMerge?: (rowIds: [number, number]) => void;
  /** Embedded in LdapAlignPage (« Rechercher manquants » tab): the title is carried by the page,
   * only the action buttons remain here (the selection lives in this component). */
  embedded?: boolean;
}

/** Empty Grist fields that the attachment will fill (civility, grade, birth). */
const complementsOf = (ldap: { civilite?: string; empCorps?: string; birthDate?: string }): string => {
  const grade = ldap.empCorps ? getGradeFromNcorps(ldap.empCorps) : null;
  return [
    ldap.civilite && i18n._(msg`title`),
    grade && i18n._(msg`grade ${grade}`),
    ldap.birthDate && i18n._(msg`birth date`),
  ].filter(Boolean).join(', ') || '—';
};

/** Label of the LDAP state (N = active, D = departure). */
const stateLabel = (etat?: string): string =>
  etat === 'N' ? i18n._(msg`active`) : etat === 'D' ? i18n._(msg`leaving`) : etat || '?';

/**
 * @component LdapCandidatesPage
 * @description Attachment of Annuaire records WITHOUT uid to their LDAP identity.
 * Phase 1 (email) + phase 2 (name): sure matches (1 candidate) are
 * checkable — email checked by default, name to confirm — and homonyms
 * (several candidates) are arbitrated by hand. « Rattacher » writes `uid_dyna`
 * (+ civility / grade / birth if empty) to Grist.
 */
export const LdapCandidatesPage: React.FC<Props> = ({ diff, progress, applying, onRerun, onApply, onMerge, embedded = false }) => {
  const { t } = useLingui();
  const proposals = diff?.proposals ?? [];
  const ambiguous = diff?.ambiguous ?? [];
  const running = !!progress?.running;

  // Selection of the sure proposals: email checked by default, name to confirm.
  const [selected, setSelected] = useState<Record<number, boolean>>({});
  // Arbitration of homonyms: gristRowId → index of the chosen candidate.
  const [arbitrated, setArbitrated] = useState<Record<number, number>>({});

  // On `diff?.generatedAt` (timestamp of the cache regenerated by a search run), not on `diff`
  // itself: `diff` changes reference at each recompute (e.g. after a partial attachment,
  // see handleApplyLdapCandidates), which cleared homonym arbitrations not yet applied
  // although the underlying cache had not changed (review lot 6a, finding 3).
  useEffect(() => {
    const init: Record<number, boolean> = {};
    for (const p of proposals) init[p.gristRowId] = p.matchedBy === 'email' && !p.duplicateOf; // duplicate → never checked by default
    setSelected(init);
    setArbitrated({});
  }, [diff?.generatedAt]); // eslint-disable-line react-hooks/exhaustive-deps

  const toggle = (rowId: number) => setSelected((s) => ({ ...s, [rowId]: !s[rowId] }));
  const selectedCount = proposals.filter((p) => selected[p.gristRowId]).length;
  const allSelected = proposals.length > 0 && selectedCount === proposals.length;
  const toggleAll = () => {
    const v = !allSelected;
    const next: Record<number, boolean> = {};
    for (const p of proposals) next[p.gristRowId] = v;
    setSelected(next);
  };
  const arbitratedCount = Object.values(arbitrated).filter((i) => (i as number) >= 0).length;

  const entries: LdapResolved[] = useMemo(() => {
    const out: LdapResolved[] = [];
    for (const p of proposals) if (selected[p.gristRowId]) out.push({ gristRowId: p.gristRowId, email: p.email, ldap: p.ldap });
    for (const a of ambiguous) {
      const idx = arbitrated[a.gristRowId];
      if (idx != null && idx >= 0 && a.candidates[idx]) out.push({ gristRowId: a.gristRowId, email: a.email, ldap: a.candidates[idx] });
    }
    return out;
  }, [proposals, ambiguous, selected, arbitrated]);

  const entryCount = entries.length;
  const progressDone = progress?.done ?? 0;
  const progressTotal = progress?.total ?? 0;
  const progressMatched = progress?.matched ?? 0;
  const progressAmbiguous = progress?.ambiguous ?? 0;

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className={`px-4 md:px-7 ${embedded ? 'pt-2' : 'pt-6'} pb-4 flex flex-wrap items-end justify-between gap-4`}>
        {embedded ? (
          <p className="text-[13px] text-muted dark:text-[#8f897c]"><Trans>Records without identifier → matching to LDAP staff (email, then name)</Trans></p>
        ) : (
          <div className="flex items-center gap-3">
            <ScanSearch className="w-7 h-7 text-ink dark:text-accent" />
            <div>
              <h2 className="font-disp text-3xl md:text-[38px] font-bold tracking-tight text-ink dark:text-[#f5f2ea] leading-none"><Trans>LDAP linking</Trans></h2>
              <p className="text-[15px] text-muted dark:text-[#8f897c] mt-1.5">
                <Trans>Records without identifier → matching to LDAP staff (email, then name)</Trans>
              </p>
            </div>
          </div>
        )}
        <div className="flex gap-3">
          <button
            onClick={onRerun}
            disabled={running}
            className="inline-flex items-center justify-center gap-2 h-11 px-5 rounded-full font-disp font-semibold text-sm bg-white/75 dark:bg-white/10 border border-white/80 dark:border-white/15 text-ink dark:text-[#f5f2ea] hover:bg-white dark:hover:bg-white/15 shadow-soft transition-colors disabled:opacity-50"
          >
            {running ? <RefreshCw className="w-4 h-4 animate-spin" /> : <ScanSearch className="w-4 h-4" />}
            {running ? t`Searching…` : t`Run LDAP search`}
          </button>
          <button
            onClick={() => onApply(entries)}
            disabled={applying || running || entries.length === 0}
            className="inline-flex items-center justify-center gap-2 h-11 px-6 rounded-full font-disp font-semibold text-sm bg-ink text-white hover:bg-black dark:bg-accent dark:text-ink dark:hover:bg-accent-strong shadow-soft transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {applying ? <RefreshCw className="w-4 h-4 animate-spin" /> : <UserCheck className="w-4 h-4" />}
            <Trans>Link selection ({entryCount})</Trans>
          </button>
        </div>
      </div>

      <div className="px-4 md:px-7 py-4 flex-1 overflow-auto space-y-8" data-page-scroll>
        {/* Progress / summary */}
        {progress && (
          <div className="text-[13px] text-muted dark:text-[#8f897c]">
            {running
              ? <Trans>Search in progress… {progressDone}/{progressTotal} records, {progressMatched} matched, <Plural value={progressAmbiguous} one="# homonym" other="# homonyms" />.</Trans>
              : progress.error
                ? <Trans>Error: {translateApiError(progress.error)}</Trans>
                : <Trans>Last search: <Plural value={progressMatched} one="# safe match" other="# safe matches" />, <Plural value={progressAmbiguous} one="# homonym to decide" other="# homonyms to decide" />.</Trans>}
          </div>
        )}
        {diff && diff.alreadyLinked > 0 && (
          <div className="text-[13px] text-muted-faint -mt-6">
            <Plural value={diff.alreadyLinked} one="# cache entry already linked in the meantime — ignored." other="# cache entries already linked in the meantime — ignored." />
          </div>
        )}

        {proposals.length === 0 && ambiguous.length === 0 ? (
          <div className="glass-card p-10 text-center">
            <p className="text-[15px] text-muted dark:text-[#8f897c]">
              {running ? t`LDAP search in progress…` : t`No suggestion. Run the LDAP search to match records without identifier.`}
            </p>
          </div>
        ) : (
          <>
            {/* Section 1: sure candidates (only 1) */}
            {proposals.length > 0 && (
              <section>
                <h3 className="font-disp text-lg font-bold tracking-tight text-ink dark:text-[#f5f2ea] mb-3">
                  <Trans>Candidates ({proposals.length}) — <Plural value={selectedCount} one="# selected" other="# selected" /></Trans>
                </h3>
                <div className="glass-card overflow-hidden">
                  <table className="w-full text-sm">
                    <thead className="border-b border-ink/5 dark:border-white/5">
                      <tr className="text-left text-[11.5px] font-bold uppercase tracking-[.09em] text-muted-lighter dark:text-[#8f897c]">
                        <th className="px-4 py-3 w-10">
                          <button onClick={toggleAll} title={t`Check / uncheck all`} className="text-muted dark:text-[#8f897c] hover:text-ink dark:hover:text-[#f5f2ea]">
                            {allSelected ? <CheckSquare className="w-4 h-4" /> : <Square className="w-4 h-4" />}
                          </button>
                        </th>
                        <th className="px-4 py-3"><Trans>Record (no uid)</Trans></th>
                        <th className="px-4 py-3"><Trans>Match</Trans></th>
                        <th className="px-4 py-3"><Trans>Lab</Trans></th>
                        <th className="px-4 py-3"><Trans>→ LDAP identity</Trans></th>
                        <th className="px-4 py-3">uid</th>
                        <th className="px-4 py-3"><Trans>Fills in</Trans></th>
                      </tr>
                    </thead>
                    <tbody>
                      {proposals.map((p) => {
                        const checked = !!selected[p.gristRowId];
                        return (
                          <tr key={p.gristRowId} className="border-b border-ink/5 dark:border-white/5 hover:bg-accent/10 transition-colors">
                            <td className="px-4 py-3">
                              <button onClick={() => toggle(p.gristRowId)}>
                                {checked ? <CheckSquare className="w-4 h-4 text-ink dark:text-accent" /> : <Square className="w-4 h-4 text-muted-faint" />}
                              </button>
                            </td>
                            <td className="px-4 py-3 font-disp font-semibold text-ink dark:text-[#f5f2ea]">
                              {String(p.nom).toUpperCase()} {p.prenom}
                              <div className="font-sans font-normal text-[12px] text-muted-light dark:text-[#8f897c]">{p.email || t`(no email)`}</div>
                            </td>
                            <td className="px-4 py-3">
                              <span className={`inline-flex items-center h-6 px-2.5 rounded-full text-[11px] font-semibold ${p.matchedBy === 'email' ? 'bg-[rgba(46,160,102,.16)] text-[#1f7a4d] dark:bg-[rgba(46,160,102,.22)] dark:text-[#5fd39a]' : 'bg-[rgba(224,158,42,.18)] text-[#9a6a12] dark:bg-[rgba(224,158,42,.22)] dark:text-[#f0c266]'}`}>
                                {p.matchedBy === 'email' ? t`email` : t`name`}
                              </span>
                            </td>
                            <td className="px-4 py-3 text-[13px] text-muted dark:text-[#8f897c]">{p.labo}</td>
                            <td className="px-4 py-3 text-[13.5px] font-medium text-ink dark:text-[#e7e2d6]">{p.ldap.displayName}</td>
                            <td className="px-4 py-3 font-mono text-[12px] font-bold text-ink dark:text-accent">{p.ldap.uid}</td>
                            <td className="px-4 py-3 text-[12px] text-muted-faint">
                              {p.duplicateOf ? (
                                <span className="inline-flex flex-wrap items-center gap-1.5">
                                  <span title={t`This uid is already carried by another row of the same lab: linking would create a duplicate.`} className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-[rgba(231,111,154,.2)] text-[#b23b3b] dark:text-[#f08c8c] text-[11px] font-bold">
                                    <Copy className="w-3 h-3" /> <Trans>duplicate of {p.duplicateOf.name}</Trans>
                                  </span>
                                  {onMerge && (
                                    <button type="button" onClick={() => onMerge([p.gristRowId, p.duplicateOf!.gristRowId])} className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-ink text-white dark:bg-accent dark:text-ink text-[11px] font-semibold hover:bg-black dark:hover:bg-accent-strong">
                                      <GitMerge className="w-3 h-3" /> <Trans>Merge</Trans>
                                    </button>
                                  )}
                                </span>
                              ) : complementsOf(p.ldap)}
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
                <p className="text-[12.5px] text-muted-light dark:text-[#8f897c] mt-2">
                  <Trans>Matches by <b>name</b> are unchecked by default (less reliable than email) — check them after verification.</Trans>
                </p>
              </section>
            )}

            {/* Section 2: homonyms to arbitrate */}
            {ambiguous.length > 0 && (
              <section>
                <h3 className="font-disp text-lg font-bold tracking-tight text-ink dark:text-[#f5f2ea] mb-3">
                  <Trans>Homonyms to decide ({ambiguous.length}) — <Plural value={arbitratedCount} one="# decided" other="# decided" /></Trans>
                </h3>
                <div className="space-y-3">
                  {ambiguous.map((a) => (
                    <div key={a.gristRowId} className="glass-card p-5">
                      <div className="flex items-baseline justify-between mb-3">
                        <div className="font-disp font-semibold text-[15px] text-ink dark:text-[#f5f2ea]">
                          {String(a.nom).toUpperCase()} {a.prenom}
                          <span className="ml-2 font-sans font-normal text-[12px] text-muted-light dark:text-[#8f897c]">{a.email || t`(no email)`} · {a.labo}</span>
                        </div>
                        <span className="text-[12px] text-muted-faint"><Plural value={a.candidates.length} one="# candidate" other="# candidates" /></span>
                      </div>
                      <div className="flex flex-col gap-1">
                        <label className="flex items-center gap-2 px-2 py-1.5 rounded-xl text-[13px] text-muted-light dark:text-[#8f897c] cursor-pointer hover:bg-accent/10 transition-colors">
                          <input
                            type="radio"
                            name={`ambig-${a.gristRowId}`}
                            checked={(arbitrated[a.gristRowId] ?? -1) === -1}
                            onChange={() => setArbitrated((m) => ({ ...m, [a.gristRowId]: -1 }))}
                            className="accent-[#1c1b19] dark:accent-[#f4d24a]"
                          />
                          <Trans>None (do not link)</Trans>
                        </label>
                        {a.candidates.map((c, idx) => (
                          <label key={c.uid} className="flex items-center gap-2 px-2 py-1.5 rounded-xl text-[13px] text-ink dark:text-[#e7e2d6] cursor-pointer hover:bg-accent/10 transition-colors">
                            <input
                              type="radio"
                              name={`ambig-${a.gristRowId}`}
                              checked={arbitrated[a.gristRowId] === idx}
                              onChange={() => setArbitrated((m) => ({ ...m, [a.gristRowId]: idx }))}
                              className="accent-[#1c1b19] dark:accent-[#f4d24a]"
                            />
                            <span className="font-mono text-[12px] font-bold text-ink dark:text-accent">{c.uid}</span>
                            <span className="text-ink dark:text-[#e7e2d6]">{c.displayName}</span>
                            <span className="text-muted-faint">· {stateLabel(c.etat)} · {complementsOf(c)}</span>
                          </label>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </section>
            )}
          </>
        )}
      </div>
    </div>
  );
};
