// Instance settings of the Cloudflare Functions (docs/plan-architecture-multi-instances.md, lots 5 c
// and 6 b).
//
// Source: the registry generated by the build (scripts/prepare-cloudflare-assets.cjs) in
// functions/_generated/registry.js — `null` when the instance has no instance.json yet, otherwise
// { mode, defaultSlug, instances: { <slug>: <validated instance.json> }, byHost: { <host>: <slug> } }:
//  - mode "single" (one Pages project = one instance, DRUID_INSTANCE): every host serves that
//    instance (pages.dev, branch previews, custom domain); Pages variables still override the
//    registry field by field when present and non-empty (transition of lot 5):
//      DRUID_INSTANCE, INSTANCE_LABEL, READ_ONLY, SHOW_STATUS_VALIDATION, ADMIN_EMAILS,
//      OPENALEX_MAILTO, GRIST_DOC_ID / VITE_GRIST_DOC_ID, GRIST_API_BASE, VITE_GRIST_PUBLIC_BASE_URL;
//  - mode "multi" (one deployment for several instances, DRUID_DEPLOYMENT or DRUID_INSTANCES): the instance is the one
//    declaring the request host in its `domains`; an unknown host gets no instance (404). No
//    variable overrides an instance, and secrets are only read per instance (see secretOf).
// Without registry nor variable, the defaults are the historical ones (Centrale).
//
// No route: this module exports no onRequest handler, so Pages does not serve it.
import registry from '../_generated/registry.js';

export const DEFAULT_SLUG = 'centrale';
export const DEFAULT_GRIST_API_BASE = 'https://grist.numerique.gouv.fr/api';
// Secrets an instance can hold. In "multi" mode they are named <NAME>__<SLUG> (see secretOf).
export const INSTANCE_SECRETS = ['GRIST_API_KEY', 'ILAAS_API_KEY', 'OPENALEX_API_KEY'];

const isSet = (v) => v !== undefined && v !== null && String(v).trim() !== '';
const isTrue = (v) => String(v || '').trim().toLowerCase() === 'true';

export const parseAdminEmails = (raw) =>
  String(raw || '').split(',').map((e) => e.trim().toLowerCase()).filter(Boolean);

/**
 * Pure resolution: registry entry (or null) + environment → runtime settings.
 * @param {Record<string, string>} env Pages environment
 * @param {object|null} reg validated instance.json, or null
 * @param {{ shared?: boolean }} [opts] shared: the deployment serves several instances — the
 *   environment then overrides nothing
 */
export const resolveInstance = (env = {}, reg = null, { shared = false } = {}) => {
  const e = shared ? {} : env;
  const slug = (isSet(e.DRUID_INSTANCE) ? String(e.DRUID_INSTANCE).trim() : reg?.slug) || DEFAULT_SLUG;
  const envBool = (name, fallback) => (isSet(e[name]) ? isTrue(e[name]) : fallback);
  const docId = [e.GRIST_DOC_ID, e.VITE_GRIST_DOC_ID, reg?.grist?.docId].find(isSet) || '';
  const apiBase = String([e.GRIST_API_BASE, reg?.grist?.apiBase].find(isSet) || DEFAULT_GRIST_API_BASE).trim().replace(/\/$/, '');
  // Public doc read directly by the browser (read-only instance): its API base, else null (proxy).
  const publicBaseUrl = isSet(e.VITE_GRIST_PUBLIC_BASE_URL)
    ? String(e.VITE_GRIST_PUBLIC_BASE_URL).trim().replace(/\/$/, '')
    : (reg?.grist?.publicRead ? apiBase : null);
  return {
    slug,
    label: String([e.INSTANCE_LABEL, reg?.label].find(isSet) || 'Centrale Nantes'),
    readOnly: envBool('READ_ONLY', !!reg?.readOnly),
    statusValidation: envBool('SHOW_STATUS_VALIDATION', !!reg?.capabilities?.HAS_STATUS_VALIDATION),
    grist: { docId: String(docId).trim(), apiBase, publicBaseUrl },
    // Without registry, news and newsletter keep their historical rule: Centrale only.
    features: {
      news: reg ? !!reg.features?.news : slug === DEFAULT_SLUG,
      newsletter: reg ? !!reg.features?.newsletter : slug === DEFAULT_SLUG,
    },
    admins: isSet(e.ADMIN_EMAILS) ? parseAdminEmails(e.ADMIN_EMAILS) : (reg?.admins || []).map((a) => a.toLowerCase()),
    openalexMailto: [e.OPENALEX_MAILTO, reg?.openalexMailto].find(isSet) || null,
    fromRegistry: !!reg,
    shared,
  };
};

/**
 * Instance serving `host`, or null (shared deployment, host declared by no instance).
 * @param {string} host request host name
 * @param {Record<string, string>} env Pages environment
 * @param {object|null} reg generated registry (see the header), or null
 */
export const resolveForHost = (host, env = {}, reg = null) => {
  if (!reg) return resolveInstance(env, null);
  const h = String(host || '').trim().toLowerCase().replace(/\.$/, '');
  if (reg.mode === 'multi') {
    const slug = Object.prototype.hasOwnProperty.call(reg.byHost || {}, h) ? reg.byHost[h] : null;
    return slug && reg.instances?.[slug] ? resolveInstance(env, reg.instances[slug], { shared: true }) : null;
  }
  return resolveInstance(env, reg.instances?.[reg.defaultSlug] || null);
};

/** Settings of the instance serving `request` (generated registry + Pages environment), or null. */
export const instanceForRequest = (request, env = {}) =>
  resolveForHost(new URL(request.url).hostname, env, registry);

/**
 * Instance of a Functions request: resolved once by functions/api/_middleware.js (context.data),
 * or here when a handler is called without it (tests, routes outside /api).
 */
export const instanceOf = (context) =>
  context.data?.instance || instanceForRequest(context.request, context.env);

/** Suffix of the per-instance secrets: `demo-2` → `DEMO_2`. */
export const secretSuffix = (slug) => String(slug).toUpperCase().replace(/[^A-Z0-9]/g, '_');

/**
 * Secret of an instance: <NAME>__<SLUG> first; the plain <NAME> only on a deployment that serves a
 * single instance — on a shared one, an instance without its own key never borrows another's.
 */
export const secretOf = (env, instance, name) => {
  const own = env[`${name}__${secretSuffix(instance.slug)}`];
  if (isSet(own)) return own;
  return instance.shared ? undefined : env[name];
};

/**
 * Environment of a handler for its instance: every secret of INSTANCE_SECRETS replaced by the
 * instance's own (secretOf), the technical variables (ILAAS_MODEL…) kept as they are.
 */
export const instanceEnv = (env, instance) => {
  const out = { ...env };
  for (const name of INSTANCE_SECRETS) {
    const v = secretOf(env, instance, name);
    if (v === undefined) delete out[name]; else out[name] = v;
  }
  return out;
};

/** Instance block of /api/me (lib/instanceRuntime.ts): what the browser needs, nothing private. */
export const publicInstanceInfo = (instance) => ({
  slug: instance.slug,
  label: instance.label,
  gristDocId: instance.grist.docId,
  gristPublicBaseUrl: instance.grist.publicBaseUrl,
  gristUiUrl: instance.grist.apiBase.replace(/\/api$/, ''),
});
