'use strict';
// Storage and access control of the « Mes rapports » reports (docs/plan-mes-rapports.md, lot 2).
//
// One module for both runtimes: server.cjs (Nantes, Express) requires it, and the Cloudflare
// Pages Function functions/api/reports/[[path]].js imports it (esbuild bundles CommonJS). It holds
// no runtime-specific code: the caller passes the user, the request and a Grist client built on
// the global `fetch`.
//
// Data: three tables of the instance's Grist doc, created on first use —
//   Rapports             one row per report; `definition` = JSON of the report (context + blocks)
//   Rapports_partages    one row per (report, grantee) with a role viewer | editor
//   Rapports_generations one row per PDF generation (resolved definition, counts, AI texts)
// These tables never go through the generic Grist proxy (its Cloudflare version cannot filter
// rows per user, see plan § 3.2): only this API reads and writes them.
//
// Validation: the server checks bounds and the outer shape of a definition (size, name, slug,
// block count); the full schema (components/dashboard/report/definition.ts, zod) is applied by
// the client before saving and again when loading, so an off-schema definition written by hand
// is refused at display time, never rendered.

const REPORTS_TABLE = 'Rapports';
const SHARES_TABLE = 'Rapports_partages';
const GENERATIONS_TABLE = 'Rapports_generations';

const text = (id, label) => ({ id, fields: { label, type: 'Text' } });
const REPORTS_COLUMNS = [
  text('owner', 'Owner'),
  text('name', 'Name'),
  text('description', 'Description'),
  text('template_id', 'Template'),
  text('definition', 'Definition (JSON)'),
  text('visibility', 'Visibility (private | instance)'),
  text('created_at', 'Created at'),
  text('updated_at', 'Updated at'),
  text('deleted_at', 'Deleted at'),
  // Published by a super admin as a template of the instance (lot 6): readable by everyone,
  // offered in « New report ».
  { id: 'published_template', fields: { label: 'Instance template', type: 'Bool' } },
];
const SHARES_COLUMNS = [
  { id: 'report', fields: { label: 'Report (row id)', type: 'Int' } },
  text('grantee', 'Grantee'),
  text('role', 'Role (viewer | editor)'),
  text('granted_by', 'Granted by'),
  text('granted_at', 'Granted at'),
];
const GENERATIONS_COLUMNS = [
  { id: 'report', fields: { label: 'Report (row id)', type: 'Int' } },
  text('generated_at', 'Generated at'),
  text('generated_by', 'Generated by'),
  text('definition_snapshot', 'Resolved definition (JSON)'),
  { id: 'publication_count', fields: { label: 'Publications', type: 'Int' } },
  text('data_date', 'Data date'),
  text('ai_texts', 'AI texts (JSON)'),
  text('pdf_ref', 'Archived PDF'),
  { id: 'shared_frozen', fields: { label: 'Shared as frozen PDF', type: 'Bool' } },
];

const LIMITS = {
  maxDefinitionBytes: 200000,
  maxSnapshotBytes: 400000,
  maxName: 200,
  maxDescription: 2000,
  maxBlocks: 150,
  maxShares: 100,
  maxGrantee: 200,
};
const SLUG_RE = /^[a-z0-9_-]{1,64}$/;
const VISIBILITIES = ['private', 'instance'];
const SHARE_ROLES = ['viewer', 'editor'];

// Error answers (status + English message declared in lib/apiErrors.ts).
const ERRORS = {
  notFound: { status: 404, error: 'Report not found' },
  forbidden: { status: 403, error: 'Not allowed on this report' },
  invalid: { status: 400, error: 'Invalid report definition' },
  conflict: { status: 409, error: 'Report changed since it was loaded' },
  invalidShare: { status: 400, error: 'Invalid report share' },
  invalidGeneration: { status: 400, error: 'Invalid report generation' },
  invalidId: { status: 400, error: 'Invalid id' },
  unknownRoute: { status: 404, error: 'Not found' },
};

class ReportsError extends Error {
  constructor(kind, detail) {
    const { status, error } = ERRORS[kind];
    super(detail ? `${error}: ${detail}` : error);
    this.status = status;
  }
}

const normId = (s) => String(s || '').trim().toLowerCase();
const byteLength = (s) => new TextEncoder().encode(s).length;
const isPlainObject = (v) => v != null && typeof v === 'object' && !Array.isArray(v);
const parseJson = (s, fallback) => {
  try { return s ? JSON.parse(s) : fallback; } catch { return fallback; }
};

/** Outer checks of a definition; returns the problem, or null. */
function definitionProblem(def) {
  if (!isPlainObject(def)) return 'not an object';
  let json;
  try { json = JSON.stringify(def); } catch { return 'not serializable'; }
  if (byteLength(json) > LIMITS.maxDefinitionBytes) return 'too large';
  if (def.schemaVersion !== 1) return 'schemaVersion';
  if (typeof def.name !== 'string' || !def.name.trim() || def.name.length > LIMITS.maxName) return 'name';
  if (typeof def.description !== 'string' || def.description.length > LIMITS.maxDescription) return 'description';
  if (!isPlainObject(def.context) || !SLUG_RE.test(String(def.context.slug || ''))) return 'context.slug';
  if (!Array.isArray(def.blocks) || def.blocks.length > LIMITS.maxBlocks) return 'blocks';
  if (def.blocks.some((b) => !isPlainObject(b) || typeof b.id !== 'string' || typeof b.kind !== 'string')) return 'blocks';
  return null;
}

// ── Grist client ─────────────────────────────────────────────────────────────

/** Minimal Grist REST client on one document. */
function gristClient({ apiBase, doc, apiKey, fetchImpl = fetch, userAgent }) {
  const headers = { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json', Accept: 'application/json' };
  if (userAgent) headers['User-Agent'] = userAgent;
  const call = async (method, path, body) => {
    const resp = await fetchImpl(`${apiBase}/docs/${doc}/${path}`, {
      method,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    if (!resp.ok) throw new Error(`Grist HTTP ${resp.status} (${method} ${path.split('?')[0]})`);
    const raw = await resp.text();
    return raw ? JSON.parse(raw) : {};
  };
  return {
    key: `${apiBase}/${doc}`,
    tables: async () => (await call('GET', 'tables')).tables || [],
    createTables: (tables) => call('POST', 'tables', { tables }),
    records: async (table, filter) => {
      const qs = filter ? `?filter=${encodeURIComponent(JSON.stringify(filter))}` : '';
      return (await call('GET', `tables/${table}/records${qs}`)).records || [];
    },
    add: async (table, rows) =>
      ((await call('POST', `tables/${table}/records`, { records: rows.map((fields) => ({ fields })) })).records || [])
        .map((r) => r.id),
    columns: async (table) => (await call('GET', `tables/${table}/columns`)).columns || [],
    addColumns: (table, columns) => call('POST', `tables/${table}/columns`, { columns }),
    update: (table, rows) => call('PATCH', `tables/${table}/records`, { records: rows }),
    remove: (table, ids) => call('POST', `tables/${table}/data/delete`, ids),
  };
}

// Tables known to exist, per document (module state: one check per process / isolate).
const readyDocs = new Map();
function ensureTables(client) {
  if (!readyDocs.has(client.key)) {
    const p = (async () => {
      const have = new Set((await client.tables()).map((t) => t.id));
      const all = [
        [REPORTS_TABLE, REPORTS_COLUMNS],
        [SHARES_TABLE, SHARES_COLUMNS],
        [GENERATIONS_TABLE, GENERATIONS_COLUMNS],
      ];
      const missing = all.filter(([id]) => !have.has(id));
      if (missing.length) await client.createTables(missing.map(([id, columns]) => ({ id, columns })));
      // Tables created by an earlier version: add the columns introduced since.
      for (const [id, columns] of all.filter(([tid]) => have.has(tid))) {
        const present = new Set((await client.columns(id)).map((c) => c.id));
        const absent = columns.filter((c) => !present.has(c.id));
        if (absent.length) await client.addColumns(id, absent);
      }
    })();
    readyDocs.set(client.key, p);
    p.catch(() => readyDocs.delete(client.key));
  }
  return readyDocs.get(client.key);
}

// ── Store ────────────────────────────────────────────────────────────────────

/**
 * @param client gristClient(...) (or a fake with the same methods, in tests)
 * @param now clock, injectable for tests
 */
function createReportsStore(client, { now = () => new Date() } = {}) {
  const stamp = () => now().toISOString();

  const summaryOf = (row, role, extra = {}) => ({
    id: row.id,
    name: row.fields.name || '',
    description: row.fields.description || '',
    templateId: row.fields.template_id || null,
    owner: row.fields.owner,
    visibility: VISIBILITIES.includes(row.fields.visibility) ? row.fields.visibility : 'private',
    createdAt: row.fields.created_at || null,
    updatedAt: row.fields.updated_at || null,
    role,
    publishedTemplate: !!row.fields.published_template,
    ...extra,
  });

  const sharesOf = async (reportIds) =>
    reportIds.length ? client.records(SHARES_TABLE, { report: reportIds }) : [];

  /** Loads a live report and the caller's role on it (throws when absent or not readable). */
  async function load(user, id) {
    if (!Number.isInteger(id) || id <= 0) throw new ReportsError('invalidId');
    // The Grist filter only works on columns, not on the row id: checked locally (as for tasks).
    const row = (await client.records(REPORTS_TABLE)).find((r) => r.id === id);
    if (!row || row.fields.deleted_at) throw new ReportsError('notFound');
    const uid = normId(user.id);
    let role = null;
    if (normId(row.fields.owner) === uid) role = 'owner';
    else {
      const share = (await sharesOf([id])).find((s) => normId(s.fields.grantee) === uid);
      if (share) role = SHARE_ROLES.includes(share.fields.role) ? share.fields.role : 'viewer';
      else if (row.fields.visibility === 'instance' || row.fields.published_template) role = 'viewer';
      else if (user.isSuperAdmin) role = 'admin';
    }
    // Not readable: answered as absent, so that ids of private reports do not leak.
    if (!role) throw new ReportsError('notFound');
    return { row, role };
  }
  const canEdit = (role) => role === 'owner' || role === 'editor';
  const canManage = (role) => role === 'owner' || role === 'admin';

  const fullOf = async (row, role) => {
    const out = summaryOf(row, role, { definition: parseJson(row.fields.definition, null) });
    if (canManage(role)) {
      out.shares = (await sharesOf([row.id])).map((s) => ({ grantee: s.fields.grantee, role: s.fields.role }));
    }
    return out;
  };

  const definitionFields = (def) => {
    const problem = definitionProblem(def);
    if (problem) throw new ReportsError('invalid', problem);
    return {
      name: def.name.trim(),
      description: def.description,
      template_id: typeof def.templateId === 'string' ? def.templateId.slice(0, 60) : '',
      definition: JSON.stringify(def),
    };
  };

  async function lastGenerations(ids) {
    const out = new Map();
    if (!ids.length) return out;
    for (const g of await client.records(GENERATIONS_TABLE, { report: ids })) {
      const at = g.fields.generated_at || '';
      if (at > (out.get(g.fields.report) || '')) out.set(g.fields.report, at);
    }
    return out;
  }

  return {
    /** Reports of the caller, shared with them, and visible to the whole instance. */
    async list(user) {
      await ensureTables(client);
      const uid = normId(user.id);
      const live = (rows) => rows.filter((r) => !r.fields.deleted_at);
      const all = live(await client.records(REPORTS_TABLE));
      const mineRows = all.filter((r) => normId(r.fields.owner) === uid);
      // Grantees are stored normalized (setShares), so the column filter is exact.
      const grants = await client.records(SHARES_TABLE, { grantee: [uid] });
      const grantRole = new Map(grants.map((s) => [s.fields.report, s.fields.role === 'editor' ? 'editor' : 'viewer']));
      const sharedRows = all.filter((r) => grantRole.has(r.id) && normId(r.fields.owner) !== uid);
      const instanceRows = all.filter((r) =>
        r.fields.visibility === 'instance' && normId(r.fields.owner) !== uid && !grantRole.has(r.id) &&
        !r.fields.published_template);
      const templateRows = all.filter((r) => r.fields.published_template);
      const ids = [...mineRows, ...sharedRows, ...instanceRows].map((r) => r.id);
      const last = await lastGenerations(ids);
      const shareCount = new Map();
      for (const s of await sharesOf(mineRows.map((r) => r.id))) {
        shareCount.set(s.fields.report, (shareCount.get(s.fields.report) || 0) + 1);
      }
      const extra = (r) => ({ lastGeneratedAt: last.get(r.id) || null });
      const byUpdate = (a, b) => String(b.updatedAt).localeCompare(String(a.updatedAt));
      return {
        mine: mineRows.map((r) => summaryOf(r, 'owner', { ...extra(r), shareCount: shareCount.get(r.id) || 0 })).sort(byUpdate),
        shared: sharedRows.map((r) => summaryOf(r, grantRole.get(r.id), extra(r))).sort(byUpdate),
        instance: instanceRows.map((r) => summaryOf(r, 'viewer', extra(r))).sort(byUpdate),
        // Instance templates, whoever owns them (the owner also sees them in `mine`).
        templates: templateRows
          .map((r) => summaryOf(r, normId(r.fields.owner) === uid ? 'owner' : 'viewer'))
          .sort((a, b) => a.name.localeCompare(b.name)),
      };
    },

    async get(user, id) {
      await ensureTables(client);
      const { row, role } = await load(user, id);
      return fullOf(row, role);
    },

    async create(user, input) {
      await ensureTables(client);
      const fields = definitionFields(input && input.definition);
      const visibility = VISIBILITIES.includes(input.visibility) ? input.visibility : 'private';
      const at = stamp();
      const [id] = await client.add(REPORTS_TABLE, [{
        ...fields, owner: user.id, visibility, created_at: at, updated_at: at, deleted_at: '', published_template: false,
      }]);
      return this.get(user, id);
    },

    /** input: { definition?, visibility?, expectedUpdatedAt? } — conflict (409) when the report moved on. */
    async update(user, id, input = {}) {
      await ensureTables(client);
      const { row, role } = await load(user, id);
      // Editors change the content; a super admin who is neither owner nor editor may only
      // change the visibility or the template flag (e.g. withdraw a report from the instance).
      if (!canEdit(role) && !(role === 'admin' && input.definition === undefined)) {
        throw new ReportsError('forbidden');
      }
      if (input.expectedUpdatedAt && input.expectedUpdatedAt !== row.fields.updated_at) {
        throw new ReportsError('conflict');
      }
      const fields = {};
      if (input.definition !== undefined) Object.assign(fields, definitionFields(input.definition));
      if (input.visibility !== undefined) {
        if (!canManage(role)) throw new ReportsError('forbidden');
        if (!VISIBILITIES.includes(input.visibility)) throw new ReportsError('invalid', 'visibility');
        fields.visibility = input.visibility;
      }
      // Publishing as an instance template: super admins only.
      if (input.publishedTemplate !== undefined) {
        if (!user.isSuperAdmin || !canManage(role)) throw new ReportsError('forbidden');
        fields.published_template = !!input.publishedTemplate;
      }
      fields.updated_at = stamp();
      await client.update(REPORTS_TABLE, [{ id, fields }]);
      return this.get(user, id);
    },

    /** Soft delete (the Cloudflare proxy has no DELETE; the history stays readable in Grist). */
    async remove(user, id) {
      await ensureTables(client);
      const { role } = await load(user, id);
      if (!canManage(role)) throw new ReportsError('forbidden');
      await client.update(REPORTS_TABLE, [{ id, fields: { deleted_at: stamp() } }]);
      return { ok: true };
    },

    /** Copy owned by the caller (any reader may duplicate), private, optionally renamed. */
    async duplicate(user, id, input = {}) {
      await ensureTables(client);
      const { row } = await load(user, id);
      const def = parseJson(row.fields.definition, null);
      if (!def) throw new ReportsError('invalid', 'stored definition');
      if (typeof input.name === 'string' && input.name.trim()) def.name = input.name.trim();
      return this.create(user, { definition: def, visibility: 'private' });
    },

    async listShares(user, id) {
      await ensureTables(client);
      const { role } = await load(user, id);
      if (!canManage(role)) throw new ReportsError('forbidden');
      return (await sharesOf([id])).map((s) => ({
        grantee: s.fields.grantee, role: s.fields.role, grantedBy: s.fields.granted_by, grantedAt: s.fields.granted_at,
      }));
    },

    /** Replaces the whole share list: [{ grantee, role }]. */
    async setShares(user, id, shares) {
      await ensureTables(client);
      const { row, role } = await load(user, id);
      if (!canManage(role)) throw new ReportsError('forbidden');
      if (!Array.isArray(shares) || shares.length > LIMITS.maxShares) throw new ReportsError('invalidShare', 'list');
      const owner = normId(row.fields.owner);
      const wanted = new Map();
      for (const s of shares) {
        const grantee = normId(s && s.grantee);
        if (!grantee || grantee.length > LIMITS.maxGrantee || !SHARE_ROLES.includes(s.role)) {
          throw new ReportsError('invalidShare', grantee || 'grantee');
        }
        if (grantee !== owner) wanted.set(grantee, s.role);
      }
      const existing = await sharesOf([id]);
      const at = stamp();
      const toRemove = existing.filter((s) => !wanted.has(normId(s.fields.grantee))).map((s) => s.id);
      const toUpdate = existing
        .filter((s) => wanted.has(normId(s.fields.grantee)) && wanted.get(normId(s.fields.grantee)) !== s.fields.role)
        .map((s) => ({ id: s.id, fields: { role: wanted.get(normId(s.fields.grantee)), granted_by: user.id, granted_at: at } }));
      const have = new Set(existing.map((s) => normId(s.fields.grantee)));
      const toAdd = [...wanted.entries()]
        .filter(([g]) => !have.has(g))
        .map(([grantee, r]) => ({ report: id, grantee, role: r, granted_by: user.id, granted_at: at }));
      if (toRemove.length) await client.remove(SHARES_TABLE, toRemove);
      if (toUpdate.length) await client.update(SHARES_TABLE, toUpdate);
      if (toAdd.length) await client.add(SHARES_TABLE, toAdd);
      return this.listShares(user, id);
    },

    async listGenerations(user, id) {
      await ensureTables(client);
      await load(user, id);
      return (await client.records(GENERATIONS_TABLE, { report: [id] }))
        .map((g) => ({
          id: g.id,
          generatedAt: g.fields.generated_at,
          generatedBy: g.fields.generated_by,
          definitionSnapshot: parseJson(g.fields.definition_snapshot, null),
          publicationCount: g.fields.publication_count ?? null,
          dataDate: g.fields.data_date || null,
          aiTexts: parseJson(g.fields.ai_texts, null),
          pdfRef: g.fields.pdf_ref || null,
          sharedFrozen: !!g.fields.shared_frozen,
        }))
        .sort((a, b) => String(b.generatedAt).localeCompare(String(a.generatedAt)));
    },

    /** Records a PDF generation — any reader may generate, the history names who did. */
    async addGeneration(user, id, input) {
      await ensureTables(client);
      await load(user, id);
      if (!isPlainObject(input)) throw new ReportsError('invalidGeneration', 'body');
      const snapshot = JSON.stringify(input.definitionSnapshot ?? null);
      const ai = JSON.stringify(input.aiTexts ?? null);
      if (byteLength(snapshot) + byteLength(ai) > LIMITS.maxSnapshotBytes) throw new ReportsError('invalidGeneration', 'too large');
      const count = input.publicationCount;
      if (count != null && (!Number.isInteger(count) || count < 0)) throw new ReportsError('invalidGeneration', 'publicationCount');
      const [genId] = await client.add(GENERATIONS_TABLE, [{
        report: id,
        generated_at: stamp(),
        generated_by: user.id,
        definition_snapshot: snapshot,
        publication_count: count ?? null,
        data_date: typeof input.dataDate === 'string' ? input.dataDate.slice(0, 40) : '',
        ai_texts: ai,
        pdf_ref: '',
        shared_frozen: false,
      }]);
      return (await this.listGenerations(user, id)).find((g) => g.id === genId);
    },
  };
}

// ── Routing (shared by server.cjs and the Pages Function) ────────────────────

/**
 * Serves /api/reports/… for an authenticated user.
 * @param req { method, segments (path after /api/reports, split), body (parsed JSON or undefined) }
 * @returns { status, body }
 */
async function routeReports(store, user, { method, segments, body }) {
  try {
    const [first, sub, ...rest] = segments.filter(Boolean);
    const ok = (payload, status = 200) => ({ status, body: payload });
    if (!first) {
      if (method === 'GET') return ok(await store.list(user));
      if (method === 'POST') return ok({ report: await store.create(user, body || {}) }, 201);
      throw new ReportsError('unknownRoute');
    }
    if (rest.length) throw new ReportsError('unknownRoute');
    if (!/^\d+$/.test(first)) throw new ReportsError('invalidId');
    const id = Number(first);
    if (!sub) {
      if (method === 'GET') return ok({ report: await store.get(user, id) });
      if (method === 'PATCH') return ok({ report: await store.update(user, id, body || {}) });
    } else if (sub === 'delete' && method === 'POST') {
      return ok(await store.remove(user, id));
    } else if (sub === 'duplicate' && method === 'POST') {
      return ok({ report: await store.duplicate(user, id, body || {}) }, 201);
    } else if (sub === 'shares') {
      if (method === 'GET') return ok({ shares: await store.listShares(user, id) });
      if (method === 'POST') return ok({ shares: await store.setShares(user, id, body && body.shares) });
    } else if (sub === 'generations') {
      if (method === 'GET') return ok({ generations: await store.listGenerations(user, id) });
      if (method === 'POST') return ok({ generation: await store.addGeneration(user, id, body || {}) }, 201);
    }
    throw new ReportsError('unknownRoute');
  } catch (e) {
    if (e instanceof ReportsError) return { status: e.status, body: { error: e.message } };
    return { status: 502, body: { error: String((e && e.message) || e) } };
  }
}

module.exports = {
  REPORTS_TABLE, SHARES_TABLE, GENERATIONS_TABLE,
  REPORTS_COLUMNS, SHARES_COLUMNS, GENERATIONS_COLUMNS,
  LIMITS, ReportsError, definitionProblem, gristClient, createReportsStore, routeReports,
};
